CREATE TABLE TBL_USER (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    TOKEN VARCHAR(1000) DEFAULT '',
    IS_ACTIVE BIT DEFAULT 1,
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_PHONE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ID_USER  VARCHAR(36) NOT NULL,
    NUMBER VARCHAR(12) NOT NULL,
    CITY_CODE VARCHAR(3) NOT NULL,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    FOREIGN KEY (ID_USER) references TBL_USER(ID),
    PRIMARY KEY (ID)
);